export type NodeCategory = "skill" | "passion" | "music" | "project" | "value" | "core";

export interface BrainNode {
  id: string;
  label: string;
  category: NodeCategory;
  description: string;
  details?: string[];
  emoji?: string;
  color: string;
  size: number;
  connections: string[];
  position?: [number, number, number];
}

export const CATEGORY_COLORS: Record<NodeCategory, string> = {
  core:    "#a78bfa",
  skill:   "#38bdf8",
  passion: "#f472b6",
  music:   "#fb923c",
  project: "#34d399",
  value:   "#facc15",
};

export const BRAIN_NODES: BrainNode[] = [
  // ── Core ──────────────────────────────────────────────────────────────────
  {
    id: "core",
    label: "Killian Pasche",
    category: "core",
    description: "Développeur full-stack de 22 ans, basé à Bouloz, Suisse.",
    details: ["Passionné, aventurier, spontané", "Code depuis 2017", "Toujours en train d'apprendre quelque chose de nouveau"],
    emoji: "🧠",
    color: CATEGORY_COLORS.core,
    size: 2.2,
    connections: ["skills-hub", "passion-hub", "music-hub", "projects-hub", "values-hub"],
    position: [0, 0, 0],
  },

  // ── Hubs ──────────────────────────────────────────────────────────────────
  {
    id: "skills-hub",
    label: "Skills",
    category: "skill",
    description: "Les technos que j'utilise au quotidien.",
    emoji: "⚡",
    color: CATEGORY_COLORS.skill,
    size: 1.5,
    connections: ["core", "nextjs", "expressjs", "react-native", "csharp", "typescript", "tailwind", "php"],
    position: [-4, 1.5, -1],
  },
  {
    id: "passion-hub",
    label: "Passions",
    category: "passion",
    description: "Ce qui me fait lever le matin.",
    emoji: "🔥",
    color: CATEGORY_COLORS.passion,
    size: 1.5,
    connections: ["core", "snowboard", "sport", "gaming", "travel", "oss"],
    position: [4, 1.5, -1],
  },
  {
    id: "music-hub",
    label: "Musique",
    category: "music",
    description: "Mon soundtrack en codant.",
    emoji: "🎵",
    color: CATEGORY_COLORS.music,
    size: 1.5,
    connections: ["core", "ninho", "niska", "tiakola", "lamano"],
    position: [0, -4, -2],
  },
  {
    id: "projects-hub",
    label: "Projets",
    category: "project",
    description: "Ce que j'ai construit.",
    emoji: "🚀",
    color: CATEGORY_COLORS.project,
    size: 1.5,
    connections: ["core", "divin", "game", "rag", "portfolio"],
    position: [-4, -2, 2],
  },
  {
    id: "values-hub",
    label: "Valeurs",
    category: "value",
    description: "Ma façon de coder et de vivre.",
    emoji: "✨",
    color: CATEGORY_COLORS.value,
    size: 1.5,
    connections: ["core", "liberte", "enthousiasme", "creativite"],
    position: [4, -2, 2],
  },

  // ── Skills ────────────────────────────────────────────────────────────────
  {
    id: "nextjs",
    label: "Next.js",
    category: "skill",
    description: "Mon framework principal.",
    details: ["App Router & Server Components", "Ce portfolio est en Next.js 15", "RAG chatbot, sites jeunesse"],
    emoji: "▲",
    color: CATEGORY_COLORS.skill,
    size: 1.2,
    connections: ["skills-hub", "typescript", "tailwind"],
  },
  {
    id: "expressjs",
    label: "Express.js",
    category: "skill",
    description: "Backend Node.js rapide et flexible.",
    details: ["APIs REST", "Middleware custom", "Utilisé sur plusieurs projets perso"],
    emoji: "🟩",
    color: CATEGORY_COLORS.skill,
    size: 1.1,
    connections: ["skills-hub", "typescript"],
  },
  {
    id: "react-native",
    label: "React Native",
    category: "skill",
    description: "Dev mobile cross-platform.",
    details: ["Projet Div-In (app de plongée)", "Expo", "iOS & Android"],
    emoji: "📱",
    color: CATEGORY_COLORS.skill,
    size: 1.0,
    connections: ["skills-hub", "divin"],
  },
  {
    id: "csharp",
    label: "C# / Unity",
    category: "skill",
    description: "Mon terrain de jeu actuel.",
    details: ["Développement de mon jeu vidéo", "Unity Engine", "La passion des origines"],
    emoji: "🎮",
    color: CATEGORY_COLORS.skill,
    size: 1.1,
    connections: ["skills-hub", "game", "gaming"],
  },
  {
    id: "typescript",
    label: "TypeScript",
    category: "skill",
    description: "JS avec un filet de sécurité.",
    details: ["Mode strict", "Typage fort sur tous mes projets", "Zod pour la validation runtime"],
    emoji: "🔷",
    color: CATEGORY_COLORS.skill,
    size: 1.0,
    connections: ["skills-hub", "nextjs"],
  },
  {
    id: "tailwind",
    label: "Tailwind CSS",
    category: "skill",
    description: "Utility-first, indispensable.",
    details: ["Tailwind v4", "Ce portfolio en est un exemple", "Design systems custom"],
    emoji: "🎨",
    color: CATEGORY_COLORS.skill,
    size: 0.9,
    connections: ["skills-hub"],
  },
  {
    id: "php",
    label: "PHP / Laravel",
    category: "skill",
    description: "Maîtrisé, backend robuste.",
    details: ["Backend de Div-In", "Laravel framework", "Bonne maîtrise, moins utilisé aujourd'hui"],
    emoji: "🐘",
    color: CATEGORY_COLORS.skill,
    size: 0.9,
    connections: ["skills-hub", "divin"],
  },

  // ── Passions ──────────────────────────────────────────────────────────────
  {
    id: "snowboard",
    label: "Snowboard & Ski",
    category: "passion",
    description: "Snowboard + peaux de phoque en montagne.",
    details: ["Ski de randonnée (peaux de phoque)", "Bivouac en altitude", "Treks hivernaux en Suisse"],
    emoji: "🏔️",
    color: CATEGORY_COLORS.passion,
    size: 1.1,
    connections: ["passion-hub", "sport"],
  },
  {
    id: "sport",
    label: "Sport & Outdoor",
    category: "passion",
    description: "Fitness, course, randonnée, trek.",
    details: ["Fitness & musculation", "Running & course à pied", "Treks & bivouac en nature"],
    emoji: "🏃",
    color: CATEGORY_COLORS.passion,
    size: 1.0,
    connections: ["passion-hub", "snowboard", "travel"],
  },
  {
    id: "gaming",
    label: "Jeux Vidéo",
    category: "passion",
    description: "La passion qui m'a amené à coder.",
    details: ["Voulais faire mon propre jeu → j'y suis !", "Joueur depuis l'enfance", "Aujourd'hui je les crée"],
    emoji: "🕹️",
    color: CATEGORY_COLORS.passion,
    size: 1.1,
    connections: ["passion-hub", "csharp", "game"],
  },
  {
    id: "travel",
    label: "Voyages",
    category: "passion",
    description: "L'aventure et la découverte.",
    details: ["Spontané et curieux", "Treks & bivouac", "Basé en Suisse, toujours en mouvement"],
    emoji: "✈️",
    color: CATEGORY_COLORS.passion,
    size: 0.9,
    connections: ["passion-hub", "sport"],
  },
  {
    id: "oss",
    label: "Open Source",
    category: "passion",
    description: "Partisan du logiciel libre.",
    details: ["Partisan de l'open source", "Toujours à l'affût des nouveautés tech", "Partage & collaboration"],
    emoji: "💻",
    color: CATEGORY_COLORS.passion,
    size: 0.9,
    connections: ["passion-hub"],
  },

  // ── Music ─────────────────────────────────────────────────────────────────
  {
    id: "ninho",
    label: "Ninho",
    category: "music",
    description: "Mon artiste préféré.",
    details: ["Album 'Comme Prévu' en tête", "Flow et énergie incomparables", "Incontournable en session de code"],
    emoji: "🎤",
    color: CATEGORY_COLORS.music,
    size: 1.2,
    connections: ["music-hub"],
  },
  {
    id: "niska",
    label: "Niska",
    category: "music",
    description: "Rap français, banger garanti.",
    details: ["Énergie pure", "Parfait pour les longues sessions", "Classique du rap FR"],
    emoji: "🔊",
    color: CATEGORY_COLORS.music,
    size: 1.0,
    connections: ["music-hub"],
  },
  {
    id: "tiakola",
    label: "Tiakola",
    category: "music",
    description: "Ambiance et flow.",
    details: ["Rap & RnB français", "Pour les sessions calmes", "Mélodies qui rentrent dans la tête"],
    emoji: "🎵",
    color: CATEGORY_COLORS.music,
    size: 0.9,
    connections: ["music-hub", "lamano"],
  },
  {
    id: "lamano",
    label: "LaMano",
    category: "music",
    description: "Dans la rotation.",
    details: ["Rap français", "Bonne énergie", "Dans mes playlists régulièrement"],
    emoji: "🎧",
    color: CATEGORY_COLORS.music,
    size: 0.85,
    connections: ["music-hub", "tiakola"],
  },

  // ── Projects ──────────────────────────────────────────────────────────────
  {
    id: "divin",
    label: "Div-In",
    category: "project",
    description: "Application de plongée mobile.",
    details: ["React Native + PHP Laravel", "iOS & Android", "Gestion de plongées et profils plongeurs"],
    emoji: "🤿",
    color: CATEGORY_COLORS.project,
    size: 1.2,
    connections: ["projects-hub", "react-native", "php"],
  },
  {
    id: "game",
    label: "Mon Jeu Vidéo",
    category: "project",
    description: "Le projet de mes rêves, en cours.",
    details: ["C# avec Unity Engine", "La raison pour laquelle j'ai commencé à coder", "Projet en développement actif"],
    emoji: "🎮",
    color: CATEGORY_COLORS.project,
    size: 1.2,
    connections: ["projects-hub", "csharp", "gaming"],
  },
  {
    id: "rag",
    label: "RAG Chatbot",
    category: "project",
    description: "Chatbot IA avec recherche documentaire.",
    details: ["Next.js + RAG (Retrieval-Augmented Generation)", "Exploration LLM & embeddings", "IA appliquée à des documents"],
    emoji: "🤖",
    color: CATEGORY_COLORS.project,
    size: 1.0,
    connections: ["projects-hub", "nextjs"],
  },
  {
    id: "portfolio",
    label: "Ce Portfolio",
    category: "project",
    description: "Mon portfolio & blog personnel.",
    details: ["Next.js 15 + Tailwind v4", "Bilingue FR / EN", "Admin panel GitHub API + MDX blog"],
    emoji: "🌐",
    color: CATEGORY_COLORS.project,
    size: 1.0,
    connections: ["projects-hub", "nextjs", "tailwind"],
  },

  // ── Values ────────────────────────────────────────────────────────────────
  {
    id: "liberte",
    label: "Liberté",
    category: "value",
    description: "Non-négociable, dans le code comme dans la vie.",
    details: ["Autonomie dans les projets", "Open source mindset", "Travailler sans contraintes inutiles"],
    emoji: "🦅",
    color: CATEGORY_COLORS.value,
    size: 1.1,
    connections: ["values-hub", "oss"],
  },
  {
    id: "enthousiasme",
    label: "Enthousiasme",
    category: "value",
    description: "Je fonce dans tout ce que je fais.",
    details: ["Passion communicative", "Toujours motivé sur les nouveaux défis", "L'énergie du premier jour, chaque jour"],
    emoji: "⚡",
    color: CATEGORY_COLORS.value,
    size: 1.0,
    connections: ["values-hub"],
  },
  {
    id: "creativite",
    label: "Créativité",
    category: "value",
    description: "Trouver des solutions originales.",
    details: ["Design & UX en plus du code", "Approche artistique du développement", "Du jeu vidéo au web, toujours créer"],
    emoji: "🎨",
    color: CATEGORY_COLORS.value,
    size: 1.0,
    connections: ["values-hub", "game"],
  },
];
